### ISSUE TITLE
Alternate Model and Lexicon formats (Human-readable or diff-able)

### ISSUE THREAD

**Issue by bhargav** [CogComp/lbjava#38]
We frequently see issues (especially in Saul) related to discrepancy in a model's performance after saving/loading it. The binary format makes it difficult to compare two models reliably.

Proposal is to allow for alternate model and lexicon formats which are human-readable or diff-able ( .json).

**Comment by danyaljj** [comment]
I absolutely support this idea. Having the possibility of saving the models as non-binary could be very helpful.

**Comment by danyaljj** [comment]
Seems like we can already do it: https://github.com/IllinoisCogComp/lbjava/blob/112bbd78e77a7253621aae8fb4499461e060c556/lbjava/src/main/java/edu/illinois/cs/cogcomp/lbjava/learn/LearnerToText.java

**Comment by bhargav** [comment]
Closing this issue. We can already print a learner to human-readable format.
